#!/bin/bash
# Automated VM Setup Script for J1-J2 Heisenberg Analysis
# This script sets up a fresh Ubuntu VM for running the complete analysis

set -e  # Exit on error

echo "=========================================="
echo "J1-J2 Heisenberg VM Setup"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

# Check if running on Ubuntu
if [ ! -f /etc/os-release ]; then
    print_error "Cannot detect OS. This script is designed for Ubuntu."
    exit 1
fi

source /etc/os-release
if [[ "$ID" != "ubuntu" ]]; then
    print_warning "This script is designed for Ubuntu. Detected: $ID"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

print_status "Detected OS: $PRETTY_NAME"

# Update system
echo ""
echo "Step 1: Updating system packages..."
sudo apt-get update -qq
sudo apt-get upgrade -y -qq
print_status "System updated"

# Install system dependencies
echo ""
echo "Step 2: Installing system dependencies..."
sudo apt-get install -y -qq \
    python3.10 \
    python3.10-venv \
    python3-pip \
    build-essential \
    git \
    wget \
    curl \
    htop \
    tmux \
    screen \
    libopenblas-dev \
    liblapack-dev \
    gfortran \
    libhdf5-dev \
    libhdf5-serial-dev \
    pkg-config

print_status "System dependencies installed"

# Check for NVIDIA GPU
echo ""
echo "Step 3: Checking for GPU..."
if command -v nvidia-smi &> /dev/null; then
    print_status "NVIDIA GPU detected"
    nvidia-smi --query-gpu=name,memory.total --format=csv,noheader
    
    # Ask if user wants to install CUDA
    read -p "Install CUDA toolkit? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Installing CUDA..."
        wget -q https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update -qq
        sudo apt-get install -y cuda-toolkit-12-1
        
        # Add to PATH
        echo 'export PATH=/usr/local/cuda/bin:$PATH' >> ~/.bashrc
        echo 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
        
        print_status "CUDA installed"
        GPU_AVAILABLE=true
    else
        GPU_AVAILABLE=false
    fi
else
    print_warning "No NVIDIA GPU detected. Will use CPU only."
    GPU_AVAILABLE=false
fi

# Create Python virtual environment
echo ""
echo "Step 4: Setting up Python environment..."
if [ -d "venv" ]; then
    print_warning "Virtual environment already exists. Skipping creation."
else
    python3.10 -m venv venv
    print_status "Virtual environment created"
fi

# Activate virtual environment
source venv/bin/activate

# Upgrade pip
pip install --upgrade pip setuptools wheel -q
print_status "pip upgraded"

# Install PyTorch
echo ""
echo "Step 5: Installing PyTorch..."
if [ "$GPU_AVAILABLE" = true ]; then
    print_status "Installing PyTorch with CUDA support..."
    pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 -q
else
    print_status "Installing PyTorch (CPU only)..."
    pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu -q
fi
print_status "PyTorch installed"

# Install project dependencies
echo ""
echo "Step 6: Installing project dependencies..."
if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt -q
    print_status "Project dependencies installed"
else
    print_error "requirements.txt not found!"
    exit 1
fi

# Create necessary directories
echo ""
echo "Step 7: Creating directory structure..."
mkdir -p data output logs checkpoints/ed_checkpoints checkpoints/qvae_models
print_status "Directories created"

# Verify installation
echo ""
echo "Step 8: Verifying installation..."
if python scripts/validation/validate_setup.py; then
    print_status "Installation verified successfully"
else
    print_error "Installation verification failed"
    exit 1
fi

# Create VM-optimized config
echo ""
echo "Step 9: Creating VM-optimized configuration..."
if [ -f "configs/vm_config.yaml" ]; then
    print_warning "VM config already exists. Skipping."
else
    # Detect number of CPU cores
    NUM_CORES=$(nproc)
    # Use 75% of cores for parallel processing
    PARALLEL_CORES=$((NUM_CORES * 3 / 4))
    if [ $PARALLEL_CORES -lt 1 ]; then
        PARALLEL_CORES=1
    fi
    
    cat > configs/vm_config.yaml << EOF
# VM-Optimized Configuration for J1-J2 Heisenberg Analysis
# Auto-generated by vm_setup.sh

ed_parameters:
  lattice_sizes: [4, 6]
  j2_j1_min: 0.3
  j2_j1_max: 0.7
  j2_j1_step: 0.01
  lanczos_tol: 1.0e-10
  use_translation_symmetry: true
  parallel: true
  n_processes: $PARALLEL_CORES  # Using $PARALLEL_CORES of $NUM_CORES available cores
  monitor_memory: true
  clear_cache_after_computation: true

qvae_architecture:
  latent_dim: 8
  encoder_layers: [512, 256, 128]
  decoder_layers: [128, 256, 512]
  
training:
  learning_rate: 0.001
  batch_size: 32
  max_epochs: 1000
  patience: 50
  beta: 0.1
  gradient_clip: 1.0
  n_random_seeds: 3
  use_gpu: $GPU_AVAILABLE
  gpu_id: null
  
analysis:
  bootstrap_samples: 1000
  correlation_threshold: 0.8
  significance_level: 0.01
  
paths:
  data_dir: "./data"
  output_dir: "./output"
  checkpoint_dir: "./checkpoints"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/j1j2_prometheus.log"
EOF
    print_status "VM config created (using $PARALLEL_CORES cores)"
fi

# Create convenience scripts
echo ""
echo "Step 10: Creating convenience scripts..."

# Create run script
cat > run_full_analysis.sh << 'EOF'
#!/bin/bash
# Run complete J1-J2 analysis

set -e

echo "=========================================="
echo "Starting J1-J2 Heisenberg Analysis"
echo "=========================================="
echo ""
echo "This will run the complete analysis pipeline."
echo "Expected runtime: 4-20 hours depending on hardware"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

# Activate environment
source venv/bin/activate

# Create timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
echo "Analysis started at: $(date)" | tee logs/analysis_${TIMESTAMP}.log

# Run pipeline
echo ""
echo "Running main pipeline..."
python main_pipeline.py --config configs/vm_config.yaml 2>&1 | tee -a logs/analysis_${TIMESTAMP}.log

# Create completion marker
touch ANALYSIS_COMPLETE
echo "Analysis completed at: $(date)" | tee -a logs/analysis_${TIMESTAMP}.log

echo ""
echo "=========================================="
echo "Analysis Complete!"
echo "=========================================="
echo ""
echo "Results are in: ./output/"
echo "Logs are in: ./logs/"
echo ""
EOF

chmod +x run_full_analysis.sh
print_status "Created run_full_analysis.sh"

# Create monitoring script
cat > monitor_progress.sh << 'EOF'
#!/bin/bash
# Monitor analysis progress

echo "=========================================="
echo "J1-J2 Analysis Progress Monitor"
echo "=========================================="
echo ""

# Check if analysis is running
if pgrep -f "main_pipeline.py" > /dev/null; then
    echo "✓ Analysis is RUNNING"
else
    echo "✗ Analysis is NOT running"
fi

echo ""
echo "Latest log entries:"
echo "-------------------"
tail -n 20 logs/j1j2_prometheus.log

echo ""
echo "Checkpoints:"
echo "------------"
ls -lh checkpoints/ed_checkpoints/ 2>/dev/null || echo "No ED checkpoints yet"
ls -lh checkpoints/qvae_models/ 2>/dev/null || echo "No Q-VAE models yet"

echo ""
echo "Output files:"
echo "-------------"
ls -lh output/ 2>/dev/null || echo "No output files yet"

echo ""
echo "System resources:"
echo "-----------------"
echo "CPU usage: $(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}')"
echo "Memory: $(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
echo "Disk: $(df -h . | awk 'NR==2 {print $3 "/" $2 " (" $5 " used)"}')"

if command -v nvidia-smi &> /dev/null; then
    echo ""
    echo "GPU usage:"
    nvidia-smi --query-gpu=utilization.gpu,memory.used,memory.total --format=csv,noheader,nounits | \
        awk '{print "  GPU: " $1 "%, Memory: " $2 "/" $3 " MB"}'
fi
EOF

chmod +x monitor_progress.sh
print_status "Created monitor_progress.sh"

# Print summary
echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
print_status "Virtual environment: venv/"
print_status "Configuration: configs/vm_config.yaml"
print_status "Parallel cores: $PARALLEL_CORES"
print_status "GPU support: $GPU_AVAILABLE"
echo ""
echo "Next steps:"
echo "  1. Review configuration: nano configs/vm_config.yaml"
echo "  2. Run analysis in tmux: tmux new -s analysis"
echo "  3. Start analysis: ./run_full_analysis.sh"
echo "  4. Monitor progress: ./monitor_progress.sh"
echo "  5. Detach from tmux: Ctrl+B, then D"
echo ""
echo "Estimated runtime: 4-20 hours (depending on hardware)"
echo ""
print_warning "Remember to run in tmux/screen to prevent disconnection issues!"
echo ""
